"""empty message

Revision ID: 759a689aea06
Revises: 997fb4ceaa48
Create Date: 2021-08-08 19:44:36.952639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759a689aea06'
down_revision = '997fb4ceaa48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
