"""completed column added  to the Todo Model

Revision ID: 997fb4ceaa48
Revises: c163fcb76f94
Create Date: 2021-08-08 19:34:30.674040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '997fb4ceaa48'
down_revision = 'c163fcb76f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
